name: Stack Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Haskell Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Build
        run: stack build && cat examples/etherscan.io/CryptoKittiesSalesAuction.evm | stack exec -- ea-bytecode-vis --outDot=work/tmp.dot && dot -Tpng work/tmp.dot -O
